[
  {
    "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/43",
    "repository_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing",
    "labels_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/43/labels{/name}",
    "comments_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/43/comments",
    "events_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/43/events",
    "html_url": "https://github.com/wisemonkeys-co/wise-billing/issues/43",
    "id": 2248973919,
    "node_id": "I_kwDOLqONmc6GDJ5f",
    "number": 43,
    "title": "Planos futuros não sendo listados",
    "user": {
      "login": "paulowhyte",
      "id": 3217623,
      "node_id": "MDQ6VXNlcjMyMTc2MjM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3217623?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paulowhyte",
      "html_url": "https://github.com/paulowhyte",
      "followers_url": "https://api.github.com/users/paulowhyte/followers",
      "following_url": "https://api.github.com/users/paulowhyte/following{/other_user}",
      "gists_url": "https://api.github.com/users/paulowhyte/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paulowhyte/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paulowhyte/subscriptions",
      "organizations_url": "https://api.github.com/users/paulowhyte/orgs",
      "repos_url": "https://api.github.com/users/paulowhyte/repos",
      "events_url": "https://api.github.com/users/paulowhyte/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paulowhyte/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 6785640442,
        "node_id": "LA_kwDOLqONmc8AAAABlHSn-g",
        "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/labels/enhancement",
        "name": "enhancement",
        "color": "a2eeef",
        "default": true,
        "description": "New feature or request"
      },
      {
        "id": 6807558855,
        "node_id": "LA_kwDOLqONmc8AAAABlcMaxw",
        "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/labels/ocs-bff-api",
        "name": "ocs-bff-api",
        "color": "6B1DCB",
        "default": false,
        "description": "Wise billing front-end API"
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/milestones/7",
      "html_url": "https://github.com/wisemonkeys-co/wise-billing/milestone/7",
      "labels_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/milestones/7/labels",
      "id": 10832120,
      "node_id": "MI_kwDOLqONmc4ApUj4",
      "number": 7,
      "title": "6.2.0",
      "description": "",
      "creator": {
        "login": "paulowhyte",
        "id": 3217623,
        "node_id": "MDQ6VXNlcjMyMTc2MjM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3217623?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/paulowhyte",
        "html_url": "https://github.com/paulowhyte",
        "followers_url": "https://api.github.com/users/paulowhyte/followers",
        "following_url": "https://api.github.com/users/paulowhyte/following{/other_user}",
        "gists_url": "https://api.github.com/users/paulowhyte/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/paulowhyte/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/paulowhyte/subscriptions",
        "organizations_url": "https://api.github.com/users/paulowhyte/orgs",
        "repos_url": "https://api.github.com/users/paulowhyte/repos",
        "events_url": "https://api.github.com/users/paulowhyte/events{/privacy}",
        "received_events_url": "https://api.github.com/users/paulowhyte/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 1,
      "closed_issues": 5,
      "state": "open",
      "created_at": "2024-04-17T16:18:21Z",
      "updated_at": "2024-05-14T13:14:14Z",
      "due_on": "2024-05-21T07:00:00Z",
      "closed_at": null
    },
    "comments": 1,
    "created_at": "2024-04-17T18:33:30Z",
    "updated_at": "2024-05-14T13:47:09Z",
    "closed_at": "2024-05-14T13:13:10Z",
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "<h2>Descrição</h2>\r\n\r\nRevalidar rota de API  GET /plans/list\r\nNão listando planos futuros\r\n\r\n<h2>Objetivos</h2>\r\n\r\n- Permitir gestão de planos ainda não vigentes em nenhuma conta\r\n\r\n<h2>Serviços</h2>\r\n\r\n### Tarefas relacionads aos serviços/domínios:\r\n[//]: # (task-start ... Não editar esta seção)\r\n- [x] ocs-bff-api\r\n\r\n\r\n\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/43/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/43/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
  },
  {
    "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/40",
    "repository_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing",
    "labels_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/40/labels{/name}",
    "comments_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/40/comments",
    "events_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/40/events",
    "html_url": "https://github.com/wisemonkeys-co/wise-billing/issues/40",
    "id": 2248840518,
    "node_id": "I_kwDOLqONmc6GCpVG",
    "number": 40,
    "title": "Novas funcionalidades para gestão de planos tarifários",
    "user": {
      "login": "paulowhyte",
      "id": 3217623,
      "node_id": "MDQ6VXNlcjMyMTc2MjM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3217623?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paulowhyte",
      "html_url": "https://github.com/paulowhyte",
      "followers_url": "https://api.github.com/users/paulowhyte/followers",
      "following_url": "https://api.github.com/users/paulowhyte/following{/other_user}",
      "gists_url": "https://api.github.com/users/paulowhyte/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paulowhyte/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paulowhyte/subscriptions",
      "organizations_url": "https://api.github.com/users/paulowhyte/orgs",
      "repos_url": "https://api.github.com/users/paulowhyte/repos",
      "events_url": "https://api.github.com/users/paulowhyte/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paulowhyte/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 6785640442,
        "node_id": "LA_kwDOLqONmc8AAAABlHSn-g",
        "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/labels/enhancement",
        "name": "enhancement",
        "color": "a2eeef",
        "default": true,
        "description": "New feature or request"
      },
      {
        "id": 6807557451,
        "node_id": "LA_kwDOLqONmc8AAAABlcMVSw",
        "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/labels/ocs-app",
        "name": "ocs-app",
        "color": "bfd4f2",
        "default": false,
        "description": "Wise billing front-end"
      },
      {
        "id": 6807558855,
        "node_id": "LA_kwDOLqONmc8AAAABlcMaxw",
        "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/labels/ocs-bff-api",
        "name": "ocs-bff-api",
        "color": "6B1DCB",
        "default": false,
        "description": "Wise billing front-end API"
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": {
      "login": "paulowhyte",
      "id": 3217623,
      "node_id": "MDQ6VXNlcjMyMTc2MjM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3217623?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paulowhyte",
      "html_url": "https://github.com/paulowhyte",
      "followers_url": "https://api.github.com/users/paulowhyte/followers",
      "following_url": "https://api.github.com/users/paulowhyte/following{/other_user}",
      "gists_url": "https://api.github.com/users/paulowhyte/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paulowhyte/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paulowhyte/subscriptions",
      "organizations_url": "https://api.github.com/users/paulowhyte/orgs",
      "repos_url": "https://api.github.com/users/paulowhyte/repos",
      "events_url": "https://api.github.com/users/paulowhyte/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paulowhyte/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "paulowhyte",
        "id": 3217623,
        "node_id": "MDQ6VXNlcjMyMTc2MjM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3217623?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/paulowhyte",
        "html_url": "https://github.com/paulowhyte",
        "followers_url": "https://api.github.com/users/paulowhyte/followers",
        "following_url": "https://api.github.com/users/paulowhyte/following{/other_user}",
        "gists_url": "https://api.github.com/users/paulowhyte/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/paulowhyte/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/paulowhyte/subscriptions",
        "organizations_url": "https://api.github.com/users/paulowhyte/orgs",
        "repos_url": "https://api.github.com/users/paulowhyte/repos",
        "events_url": "https://api.github.com/users/paulowhyte/events{/privacy}",
        "received_events_url": "https://api.github.com/users/paulowhyte/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": {
      "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/milestones/7",
      "html_url": "https://github.com/wisemonkeys-co/wise-billing/milestone/7",
      "labels_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/milestones/7/labels",
      "id": 10832120,
      "node_id": "MI_kwDOLqONmc4ApUj4",
      "number": 7,
      "title": "6.2.0",
      "description": "",
      "creator": {
        "login": "paulowhyte",
        "id": 3217623,
        "node_id": "MDQ6VXNlcjMyMTc2MjM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3217623?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/paulowhyte",
        "html_url": "https://github.com/paulowhyte",
        "followers_url": "https://api.github.com/users/paulowhyte/followers",
        "following_url": "https://api.github.com/users/paulowhyte/following{/other_user}",
        "gists_url": "https://api.github.com/users/paulowhyte/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/paulowhyte/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/paulowhyte/subscriptions",
        "organizations_url": "https://api.github.com/users/paulowhyte/orgs",
        "repos_url": "https://api.github.com/users/paulowhyte/repos",
        "events_url": "https://api.github.com/users/paulowhyte/events{/privacy}",
        "received_events_url": "https://api.github.com/users/paulowhyte/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 1,
      "closed_issues": 5,
      "state": "open",
      "created_at": "2024-04-17T16:18:21Z",
      "updated_at": "2024-05-14T13:14:14Z",
      "due_on": "2024-05-21T07:00:00Z",
      "closed_at": null
    },
    "comments": 1,
    "created_at": "2024-04-17T17:36:47Z",
    "updated_at": "2024-05-14T13:47:14Z",
    "closed_at": "2024-05-14T13:14:14Z",
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "<h2>Descrição</h2>\r\n\r\nImplementar funcionalidades de criação e cópia e migração de planos das contas.\r\n\r\n<h2>Objetivos</h2>\r\n\r\n- Permitir a criação de um plano vazio\r\n- Permitir a criação de um plano utilizando outro como modelo\r\n- Permitir a migração de um plano utilizado por múltiplas contas para um novo plano pré criado\r\n\r\n<h2>Requisitos</h2>\r\n\r\n- A funcionalidade de migração deve emitir alertas para tentativas de início de vigências no passado\r\n- Confirmação de operação de migração ( não pode ser revertida )\r\n\r\n<h2>Serviços</h2>\r\n\r\n### Tarefas relacionadas aos serviços/domínios:\r\n[//]: # (task-start ... Não editar esta seção)\r\n- [x] ocs-app\r\n- [x] ocs-bff-api\r\n\r\n<h2>Detalhamento</h2>\r\n\r\n### UI Planos\r\n\r\n<img width=\"1577\" alt=\"Screenshot 2024-04-17 at 14 10 30\" src=\"https://github.com/wisemonkeys-co/wise-billing/assets/3217623/6235573d-a8df-4460-b155-1d5f143d0c77\">\r\n\r\n\r\nPayload  POST /plans/clone\r\n```\r\npayload {\r\n    sourceID string \r\n    name     string \r\n    description string \r\n}\r\n```\r\n### Modal 1\r\n\r\n![Screenshot 2024-04-17 at 14 51 51](https://github.com/wisemonkeys-co/wise-billing/assets/3217623/1efc4f9c-31d7-43ac-8589-ad3eaaa01dbd)\r\n\r\nCaso a data escolhida seja menor que a data de hj exibir alerta para confirmação com a mensagem \"A escolha da vigência do novo plano a partir de datas no passado podem requerer retarifação e refaturamento de eventos tarifáveis a partir desta data.\" com botões de \"Cancelar\" ou  \"Migrar plano das contas\"\r\n\r\nPayload  PATCH /accounts/plans\r\n```\r\npayload {\r\n    currentPlanID string \r\n    newPlanID     string \r\n    from   date \r\n}\r\n```\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/40/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/40/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
  },
  {
    "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/39",
    "repository_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing",
    "labels_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/39/labels{/name}",
    "comments_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/39/comments",
    "events_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/39/events",
    "html_url": "https://github.com/wisemonkeys-co/wise-billing/issues/39",
    "id": 2248752049,
    "node_id": "I_kwDOLqONmc6GCTux",
    "number": 39,
    "title": "Ajuste na sidebar da Home page",
    "user": {
      "login": "paulowhyte",
      "id": 3217623,
      "node_id": "MDQ6VXNlcjMyMTc2MjM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3217623?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paulowhyte",
      "html_url": "https://github.com/paulowhyte",
      "followers_url": "https://api.github.com/users/paulowhyte/followers",
      "following_url": "https://api.github.com/users/paulowhyte/following{/other_user}",
      "gists_url": "https://api.github.com/users/paulowhyte/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paulowhyte/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paulowhyte/subscriptions",
      "organizations_url": "https://api.github.com/users/paulowhyte/orgs",
      "repos_url": "https://api.github.com/users/paulowhyte/repos",
      "events_url": "https://api.github.com/users/paulowhyte/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paulowhyte/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 6785640442,
        "node_id": "LA_kwDOLqONmc8AAAABlHSn-g",
        "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/labels/enhancement",
        "name": "enhancement",
        "color": "a2eeef",
        "default": true,
        "description": "New feature or request"
      },
      {
        "id": 6807557451,
        "node_id": "LA_kwDOLqONmc8AAAABlcMVSw",
        "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/labels/ocs-app",
        "name": "ocs-app",
        "color": "bfd4f2",
        "default": false,
        "description": "Wise billing front-end"
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/milestones/7",
      "html_url": "https://github.com/wisemonkeys-co/wise-billing/milestone/7",
      "labels_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/milestones/7/labels",
      "id": 10832120,
      "node_id": "MI_kwDOLqONmc4ApUj4",
      "number": 7,
      "title": "6.2.0",
      "description": "",
      "creator": {
        "login": "paulowhyte",
        "id": 3217623,
        "node_id": "MDQ6VXNlcjMyMTc2MjM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3217623?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/paulowhyte",
        "html_url": "https://github.com/paulowhyte",
        "followers_url": "https://api.github.com/users/paulowhyte/followers",
        "following_url": "https://api.github.com/users/paulowhyte/following{/other_user}",
        "gists_url": "https://api.github.com/users/paulowhyte/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/paulowhyte/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/paulowhyte/subscriptions",
        "organizations_url": "https://api.github.com/users/paulowhyte/orgs",
        "repos_url": "https://api.github.com/users/paulowhyte/repos",
        "events_url": "https://api.github.com/users/paulowhyte/events{/privacy}",
        "received_events_url": "https://api.github.com/users/paulowhyte/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 1,
      "closed_issues": 5,
      "state": "open",
      "created_at": "2024-04-17T16:18:21Z",
      "updated_at": "2024-05-14T13:14:14Z",
      "due_on": "2024-05-21T07:00:00Z",
      "closed_at": null
    },
    "comments": 1,
    "created_at": "2024-04-17T16:49:12Z",
    "updated_at": "2024-05-14T13:45:11Z",
    "closed_at": "2024-05-14T13:14:13Z",
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "<h2>Descrição</h2>\r\n\r\nAlterar ordem dos sub ítens  do ítem \"Configuração\"\r\n\r\n<h2>Objetivos</h2>\r\n\r\n- Ordenação cronológica de configuração dos conceitos\r\n\r\n<h2>Serviços</h2>\r\n\r\n### Tarefas relacionads aos serviços/domínios:\r\n[//]: # (task-start ... Não editar esta seção)\r\n- [x] ocs-app\r\n\r\n<h2>Detalhamento</h2>\r\n\r\n![Screenshot 2024-04-17 at 10 59 40](https://github.com/wisemonkeys-co/wise-billing/assets/3217623/7116c197-ef9e-4d9a-ae0e-60d32d552e56)\r\n\r\n\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/39/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/39/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
  },
  {
    "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/38",
    "repository_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing",
    "labels_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/38/labels{/name}",
    "comments_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/38/comments",
    "events_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/38/events",
    "html_url": "https://github.com/wisemonkeys-co/wise-billing/issues/38",
    "id": 2248692992,
    "node_id": "I_kwDOLqONmc6GCFUA",
    "number": 38,
    "title": "Alteração da UI de perfil do usuário",
    "user": {
      "login": "paulowhyte",
      "id": 3217623,
      "node_id": "MDQ6VXNlcjMyMTc2MjM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3217623?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paulowhyte",
      "html_url": "https://github.com/paulowhyte",
      "followers_url": "https://api.github.com/users/paulowhyte/followers",
      "following_url": "https://api.github.com/users/paulowhyte/following{/other_user}",
      "gists_url": "https://api.github.com/users/paulowhyte/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paulowhyte/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paulowhyte/subscriptions",
      "organizations_url": "https://api.github.com/users/paulowhyte/orgs",
      "repos_url": "https://api.github.com/users/paulowhyte/repos",
      "events_url": "https://api.github.com/users/paulowhyte/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paulowhyte/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 6785640442,
        "node_id": "LA_kwDOLqONmc8AAAABlHSn-g",
        "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/labels/enhancement",
        "name": "enhancement",
        "color": "a2eeef",
        "default": true,
        "description": "New feature or request"
      },
      {
        "id": 6807557451,
        "node_id": "LA_kwDOLqONmc8AAAABlcMVSw",
        "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/labels/ocs-app",
        "name": "ocs-app",
        "color": "bfd4f2",
        "default": false,
        "description": "Wise billing front-end"
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/milestones/7",
      "html_url": "https://github.com/wisemonkeys-co/wise-billing/milestone/7",
      "labels_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/milestones/7/labels",
      "id": 10832120,
      "node_id": "MI_kwDOLqONmc4ApUj4",
      "number": 7,
      "title": "6.2.0",
      "description": "",
      "creator": {
        "login": "paulowhyte",
        "id": 3217623,
        "node_id": "MDQ6VXNlcjMyMTc2MjM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3217623?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/paulowhyte",
        "html_url": "https://github.com/paulowhyte",
        "followers_url": "https://api.github.com/users/paulowhyte/followers",
        "following_url": "https://api.github.com/users/paulowhyte/following{/other_user}",
        "gists_url": "https://api.github.com/users/paulowhyte/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/paulowhyte/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/paulowhyte/subscriptions",
        "organizations_url": "https://api.github.com/users/paulowhyte/orgs",
        "repos_url": "https://api.github.com/users/paulowhyte/repos",
        "events_url": "https://api.github.com/users/paulowhyte/events{/privacy}",
        "received_events_url": "https://api.github.com/users/paulowhyte/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 1,
      "closed_issues": 5,
      "state": "open",
      "created_at": "2024-04-17T16:18:21Z",
      "updated_at": "2024-05-14T13:14:14Z",
      "due_on": "2024-05-21T07:00:00Z",
      "closed_at": null
    },
    "comments": 1,
    "created_at": "2024-04-17T16:14:22Z",
    "updated_at": "2024-05-14T13:53:42Z",
    "closed_at": "2024-05-14T13:14:12Z",
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "<h2>Descrição</h2>\r\n\r\nIncluir o \"Full Name\" do lado esquerdo do avatar\r\nAlterar itens e link do menu dropdown do usuário\r\n\r\n<h2>Objetivos</h2>\r\n\r\n- Permitir visualização e atualização de dados do perfil do usuário\r\n\r\n<h2>Requisitos</h2>\r\n\r\n- Manter informações de email e papel(role) somente leitura\r\n\r\n<h2>Serviços</h2>\r\n\r\n### Tarefas relacionads aos serviços/domínios:\r\n[//]: # (task-start ... Não editar esta seção)\r\n- [x] ocs-app\r\n\r\n<h2>Detalhamento</h2>\r\n\r\n![Screenshot 2024-04-17 at 10 55 25](https://github.com/wisemonkeys-co/wise-billing/assets/3217623/d338481a-dd38-4130-a4bf-1c91fd361c1e)\r\n\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/38/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/38/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
  },
  {
    "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/15",
    "repository_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing",
    "labels_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/15/labels{/name}",
    "comments_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/15/comments",
    "events_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/15/events",
    "html_url": "https://github.com/wisemonkeys-co/wise-billing/issues/15",
    "id": 2236291449,
    "node_id": "I_kwDOLqONmc6FSxl5",
    "number": 15,
    "title": "Incluir modelos de filtros nos escopos de conta",
    "user": {
      "login": "paulowhyte",
      "id": 3217623,
      "node_id": "MDQ6VXNlcjMyMTc2MjM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3217623?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paulowhyte",
      "html_url": "https://github.com/paulowhyte",
      "followers_url": "https://api.github.com/users/paulowhyte/followers",
      "following_url": "https://api.github.com/users/paulowhyte/following{/other_user}",
      "gists_url": "https://api.github.com/users/paulowhyte/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paulowhyte/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paulowhyte/subscriptions",
      "organizations_url": "https://api.github.com/users/paulowhyte/orgs",
      "repos_url": "https://api.github.com/users/paulowhyte/repos",
      "events_url": "https://api.github.com/users/paulowhyte/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paulowhyte/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 6785640442,
        "node_id": "LA_kwDOLqONmc8AAAABlHSn-g",
        "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/labels/enhancement",
        "name": "enhancement",
        "color": "a2eeef",
        "default": true,
        "description": "New feature or request"
      },
      {
        "id": 6807557451,
        "node_id": "LA_kwDOLqONmc8AAAABlcMVSw",
        "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/labels/ocs-app",
        "name": "ocs-app",
        "color": "bfd4f2",
        "default": false,
        "description": "Wise billing front-end"
      },
      {
        "id": 6807558855,
        "node_id": "LA_kwDOLqONmc8AAAABlcMaxw",
        "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/labels/ocs-bff-api",
        "name": "ocs-bff-api",
        "color": "6B1DCB",
        "default": false,
        "description": "Wise billing front-end API"
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/milestones/7",
      "html_url": "https://github.com/wisemonkeys-co/wise-billing/milestone/7",
      "labels_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/milestones/7/labels",
      "id": 10832120,
      "node_id": "MI_kwDOLqONmc4ApUj4",
      "number": 7,
      "title": "6.2.0",
      "description": "",
      "creator": {
        "login": "paulowhyte",
        "id": 3217623,
        "node_id": "MDQ6VXNlcjMyMTc2MjM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3217623?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/paulowhyte",
        "html_url": "https://github.com/paulowhyte",
        "followers_url": "https://api.github.com/users/paulowhyte/followers",
        "following_url": "https://api.github.com/users/paulowhyte/following{/other_user}",
        "gists_url": "https://api.github.com/users/paulowhyte/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/paulowhyte/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/paulowhyte/subscriptions",
        "organizations_url": "https://api.github.com/users/paulowhyte/orgs",
        "repos_url": "https://api.github.com/users/paulowhyte/repos",
        "events_url": "https://api.github.com/users/paulowhyte/events{/privacy}",
        "received_events_url": "https://api.github.com/users/paulowhyte/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 1,
      "closed_issues": 5,
      "state": "open",
      "created_at": "2024-04-17T16:18:21Z",
      "updated_at": "2024-05-14T13:14:14Z",
      "due_on": "2024-05-21T07:00:00Z",
      "closed_at": null
    },
    "comments": 1,
    "created_at": "2024-04-10T19:33:57Z",
    "updated_at": "2024-05-14T13:49:20Z",
    "closed_at": "2024-05-14T13:14:12Z",
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "Permitir que APIs de integração utilizem modelos de strings de roteamento de eventos dentro dos escopos de conta.\r\n\r\n<h2>Objetivos</h2>\r\n\r\n- Permitir roteamento de eventos para escopos de faturamento separados, definidos por informações contidas nos eventos tarifáveis ( arquivos ou streaming )\r\n\r\n<h2>Requisitos</h2>\r\n\r\n- Configurável através do front-end apenas em contas do tipo \"template\"\r\n\r\n<h2>Serviços</h2>\r\n\r\n### Tarefas relacionads aos serviços/domínios:\r\n[//]: # (task-start ... Não editar esta seção)\r\n- [ ] ocs-app\r\n- [ ] ocs-bff-api\r\n\r\n<h2>Detalhamento</h2>\r\n\r\n![issue](https://github.com/wisemonkeys-co/wise-billing/assets/3217623/6c4f0607-b7f4-490f-a045-3560541c17fc)\r\n\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/15/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/wisemonkeys-co/wise-billing/issues/15/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
  }
]
