name: Issues Sync
on:
  issues:
    types: [labeled, unlabeled]
env:
  REPO_TOKEN: ${{ secrets.WISE_CD_REPO_TOKEN }}
  GIT_ORG:    wisemonkeys-co 
  VERSION:    6.2.0
jobs:  
  sync:    
    name: Sync Issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      #- run: gh issue edit "$NUMBER" --add-label "$LABELS"
      - run: echo "$NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
    #  - name: Message Dispatch to HMG CD     
    #    run:  curl -X POST --header "Accept:application/vnd.github.v3+json" --header "Authorization:token $CD_REPO_TOKEN" https://api.github.com/repos/$CD_REPO/dispatches 
    #         -d '{"event_type":"issue-update","client_payload":{"parentBranch":"'$IMAGE_NAME'","imageTag":"'$IMAGE_TAG'","releaseNotes":" v '$IMAGE_TAG'"}}'