name: Issues Sync
on:
  issues:
    types: [labeled, unlabeled]
env:
  REPO_TOKEN: ${{ secrets.WISE_CD_REPO_TOKEN }}
  GIT_ORG:    wisemonkeys-co 
  VERSION:    6.2.0
jobs:  
  sync:    
    name: Sync Issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      #- run: gh issue edit "$NUMBER" --add-label "$LABELS"
      - name: Link sub issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PARENT_ISSUE: ${{ github.event.issue.number }}
          LABEL: ${{ github.event.label.name }}
        run: |
           echo $LABEL
          # curl -X POST --header "Accept:application/vnd.github.v3+json" --header "Authorization:token $CD_REPO_TOKEN" https://api.github.com/repos/$GIT_ORG/dispatches 
          # -d '{"event_type":"issue-update","client_payload":{"parentIssue":"'$PARENT_ISSUE'"}}'