name: Link issue
on:
  issues:
    types: [closed]
env:
  REPO_TOKEN:   ${{ secrets.WISE_CD_REPO_TOKEN }}
  ORGANIZATION: wisemonkeys-co 
  PRODUCT:      wise-billing
  PROJECT_ID:   1
  GH_TOKEN:     ${{ secrets.GITHUB_TOKEN }}
  GH_REPO:      ${{ github.repository }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  ISSUE_TITLE:  ${{ github.event.issue.title }}
  LABEL:        ${{ github.event.label.name }}
  ACTION:       ${{ github.event.action }}
  
jobs:  
  link:    
    name: Link sub Issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  
      - run: | 
         echo "Buit in label"
         echo "event name is:" ${{ github.event_name }} 
         echo "event type is:" ${{ github.event.action }} 
         echo "issue: "$ISSUE_NUMBER
         echo "repo:  "$LABEL
         scripts/update-task.sh $REPO_TOKEN add $ISSUE_NUMBER $LABEL
  unlink:    
    name: Unlink sub Issue
    runs-on: ubuntu-latest

    steps:
      - run: | 
         echo "Buit in label"
         echo "event name is:" ${{ github.event_name }} 
         echo "event type is:" ${{ github.event.action }} 
         echo "issue: "$ISSUE_NUMBER
         echo "repo:  "$LABEL
         scripts/update-task.sh $REPO_TOKEN del $ISSUE_NUMBER $LABEL

#         if: github.event_name == 'labeled' &&  ! contains(fromJSON('["bug", "enhancement"]'), github.event.label.name ) 
#         if: github.event_name == 'unlabeled' &&  ! contains(fromJSON('["bug", "enhancement"]'), github.event.label.name )

  # notify:
  #   name: Notify service repo
  #   runs-on: ubuntu-latest
  #   if: ! contains(fromJSON('["bug", "enhancement"]'), github.event.label.name )
  #   steps:
  #     - run:  curl -X POST --header "Accept:application/vnd.github.v3+json" --header "Authorization:token $REPO_TOKEN" https://api.github.com/repos/$ORGANIZATION/$LABEL/dispatches 
  #             -d '{"event_type":"parent-issue-updated","client_payload":{"action":"'$ACTION'","repo":"'$LABEL'","issue":{"number":"'$ISSUE_NUMBER'","title":"'"$ISSUE_TITLE"'"},"product":{"name":"'$PRODUCT'","organization":"'$ORGANIZATION'","projectId":"'$PROJECT_ID'"}}}'

#   if: github.event.pull_request.merged == true